using Microsoft.Build.Framework;

namespace Timestamp;

public class AddTimestamp : Microsoft.Build.Utilities.Task
{
    [Required]
    public string ProjectFile { get; set; } = null!;

    [Output]
    public string TimestampAttributeTempFilePath { get; set; } = null!;

    public override bool Execute()
    {
        try
        {
            TempFileTracker.DeleteTempFiles();

            CreateTempAssemblyInfo();

            return true;
        }
        catch (Exception exception)
        {
            BuildEngine.LogErrorEvent(new("", "", null, 0, 0, 0, 0, "Error occurred: " + exception, "", "Timestamp"));
            return false;
        }
    }

    void CreateTempAssemblyInfo()
    {
        var timestampUsage =
            $"""

             // <auto-generated/>
             using Timestamp;
             [assembly: Timestamp("{DateTime.UtcNow:yyyy-MM-ddTHH:mm:ss.fffZ}")]

             """;

        var tempFileContent = timestampUsage + AttributeReader.TimestampAttribute;

        var tempFileName = $"Timestamp_{Path.GetFileNameWithoutExtension(ProjectFile)}_{Path.GetRandomFileName()}.cs";
        TimestampAttributeTempFilePath = Path.Combine(TempFileTracker.TempPath, tempFileName);
        File.WriteAllText(TimestampAttributeTempFilePath, tempFileContent);
    }
}